version: '2'
services: 
  web:
    image: ./web
    environment:
      - DEBUG=0
      - STATIC_URL=http://localhost:80/
    ports: 
      - "8000:8000"
    command: bash -c 'python manage.py migrate && uwsgi --ini uwsgi.ini'
    volumes: 
      - /usr/src/app

  nginx:
    image: nginx:1
    volumes: 
      - ./web/src/static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on: 
      - web
