version: '2'
services: 
  django:
    build: ./django
    environment: 
      - STATIC_URL=http://localhost:80/
    ports: 
      - "8000:8000"
    depends_on: 
      - rabbitmq

  celery:
    build: ./celery
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  rabbitmq:
    build: ./rabbitmq

  nginx:
    build: ./nginx
    volumes: 
      - ./django/src/static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on: 
      - django
