version: '2'
services: 
  django:
    build: ./django
    environment: 
      - STATIC_URL=http://localhost:80/
    ports: 
      - "8000:8000"
    command: bash -c 'python manage.py migrate && uwsgi --ini uwsgi.ini'
    depends_on: 
      - rabbitmq

  celery:
    build: ./celery

  rabbitmq:
    build: ./rabbitmq

  nginx:
    build: ./nginx
    volumes: 
      - ./web/src/static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on: 
      - web
